# Generated by Django 5.1.2 on 2024-11-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_price_alter_bb_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
