# Generated by Django 5.1.2 on 2024-11-11 11:51

import bboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Aa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[(None, 'Выберите тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю'), ('a', 'Отдам')], default='b', max_length=1)),
                ('title', models.CharField(error_messages={'invalid': 'Введите 4 и более символа'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Товар')),
                ('content', models.TextField(blank=True, error_messages={'invalid': 'Введите 5 и более символа'}, null=True, validators=[django.core.validators.RegexValidator(regex='^.{5,}$')], verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[bboard.models.validation_even], verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published', 'title'],
                'unique_together': {('title', 'published')},
            },
        ),
    ]
