# Generated by Django 5.1.2 on 2025-01-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_message_privatemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': []},
        ),
    ]
