# Generated by Django 5.1.2 on 2024-12-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_superprivatemessage_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superprivatemessage',
            options={'ordering': ['-content']},
        ),
    ]
