# Generated by Django 5.1.2 on 2025-01-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_message_options_alter_privatemessage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='user',
        ),
    ]
