# Generated by Django 5.1.2 on YYYY-MM-DD HH:MM
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Если tasks не зависит от других приложений, оставьте пустым.
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ] 